version: '3.4'

services:
  datahub-frontend:
    image: datahub-frontend
    build:
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      REACT_APP_THEME_CONFIG: theme_light.config.json
      SKIP_PREFLIGHT_CHECK: true
      REACT_APP_PROXY_TARGET: http://localhost:9002
    ports:
      - 80:80
